[project]
name = "mcp-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=0.3.2",
    "mcp-use>=1.2.12",
    "mcp[cli]>=1.9.0",
    "nest-asyncio>=1.6.0",
]
